common: &common
  adapter: postgresql
  username: cursive
  password: GMR900976PL0
  host: localhost

development:
  <<: *common
  database: cursive_development

test:
  <<: *common
  database: cursive_test

production:
  <<: *common
  database: cursive_production